language: node_js

os:
  - windows
  - linux
  - osx

matrix:
  include:
  - node_js: "lts/boron"
    env: ZF_TRAVIS_COMMAND=test:javascript:units
  - node_js: "lts/carbon"
    env: ZF_TRAVIS_COMMAND=test:javascript:units
  - node_js: "stable"
    env: ZF_TRAVIS_COMMAND=test:javascript:units
  - node_js: "stable"
    env: ZF_TRAVIS_COMMAND=test:javascript:browserstack

before_install:
  - npm install -g npm@latest
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then iex (new-object net.webclient).downloadstring('https://get.scoop.sh'); fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then scoop install curl; fi
install: npm ci
script: npm run $ZF_TRAVIS_COMMAND

notifications:
  email: false
